name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.12"
            target: "x86_64-unknown-linux-gnu"
          - os: windows-latest
            python-version: "3.12"
            target: "x86_64-pc-windows-msvc"
          - os: macos-latest
            python-version: "3.12"
            target: "x86_64-apple-darwin"
    runs-on: ${{ matrix.os }}
    environment: pypi

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.6.1"

      - name: Set up Cargo and Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Build Wheels with Maturin
        run: |
          poetry install
          poetry run poe build

      - name: Prepare for Publishing
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Running in test mode - no publish"
          echo "Python Version:"
          echo ${{ secrets.PYPI_TOKEN }}
          poetry run python --version
          echo "List installed packages"
          poetry run pip list

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo $PYPI_TOKEN
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --format wheel --file dist/*.whl
